### DISCUSSION TITLE
Role Editor for community.grafana.grafana_datasource Module

### DISCUSSION THREAD

**Discussion by ishk0** [ansible-collections/community.grafana#409] [Q&A]
Hello,
I am using:

- grafana_version: 11.1.3
- grafana_package_arch: amd64

My community.grafana.grafana_datasource module configuration:

```
---
- name: Process datasources
  community.grafana.grafana_datasource: {}
  args: '{{ grafana_manager_credentials | combine(item) }}'
  loop: '{{ grafana_manager_datasources }}'
  loop_control:
    label: '{{ item.name }}'
  tags:
    - grafana-datasources
    - grafana_datasources

  - name: Alpha
    ds_type: postgres
    ds_url: '{{ acc.addr }}:5432'
    database: '{{ acc.alpha.db }}'
    user: '{{ accs.anal.user }}'
    password: '{{ acc.anal.ps }}'
    enforce_secure_data: true
```
I noticed that a Grafana user with the Editor role cannot perform a SELECT operation on this Alpha datasource. However, if I manually create an identical Alpha-man datasource, the Editor role has SELECT access.

If I grant the admin role to the user, SELECT works for both datasources.

Could you please help me understand how to configure the role correctly? Thank you!
