### ISSUE TITLE
Some way to add own/additional jsonData

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.grafana#101]
##### SUMMARY
Currently there is now way to add some additional/custom jsonData which would be beneficial to handle data needed or wanted by the datasources. Like `alerting` for zabbix as example. Current provided properties can of course override the given data.

Adding all the additional options as module parameters wouldn't be too handy.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
grafana_datasource

##### ADDITIONAL INFORMATION

```yaml
    - community.grafana.grafana_datasource:
        name: "Zabbix"
        ds_type: "alexanderzobnin-zabbix-datasource"
        access: "proxy"
        ds_url: "http://zabbix/api_jsonrpc.php"
        is_default: false
        additional_jsonData:
          addThresholds: false
          alerting: false
          alertingMinSeverity: 3
```
