### ISSUE TITLE
grafana_datasource reports 'changed' for repeated runs

### ISSUE THREAD

**Issue by ecksun** [ansible-collections/community.grafana#127]
##### SUMMARY
grafana_datasource module reports 'changed' for each run even if nothing has been changed in datasoure.

I'm simply migrating this from https://github.com/ansible/ansible/issues/51068 which wasn't migrated automatically.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_datasource

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/amarao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 28 2018, 16:27:22) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=10s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%r
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -H -S
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

local: Ubuntu 19.04
remote: Ubuntu 18.04, grafana 5.4.2

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
   - name: Configure datasource
     grafana_datasource:
       name: influx
       access: proxy
       basic_auth_user: admin
       basic_auth_password: admin
       ds_type: influxdb
       database: '{{ torture_database }}'
       grafana_url: http://127.0.0.1:3000
       grafana_user: admin
       grafana_password: admin
       is_default: true
       tls_skip_verify: true
       url: http://127.0.0.1:8086
```

##### EXPECTED RESULTS

changed only on first run.

##### ACTUAL RESULTS

```paste below
ansible-playbook test.yaml
changed=1

ansible-playbook test.yaml
changed=1
```

**Comment by ecksun** [comment]
Migrating [this comment](https://github.com/ansible/ansible/issues/51068#issuecomment-472030318)

I'm seeing the same thing, as additional information this is the output of the task:

```json
{
    "foobar": {
        "after": {
            "access": "proxy",
            "basicAuth": false,
            "database": null,
            "id": 2,
            "isDefault": false,
            "jsonData": {
                "tlsAuth": false,
                "tlsAuthWithCACert": false
            },
            "name": "prometheus",
            "orgId": 1,
            "password": "",
            "type": "prometheus",
            "url": "http://localhost:9090",
            "user": "",
            "withCredentials": false
        },
        "before": {
            "access": "proxy",
            "basicAuth": false,
            "database": "",
            "id": 2,
            "isDefault": false,
            "jsonData": {
                "tlsAuth": false,
                "tlsAuthWithCACert": false
            },
            "name": "prometheus",
            "orgId": 1,
            "password": "",
            "readOnly": true,
            "type": "prometheus",
            "url": "http://localhost:9090",
            "user": "",
            "version": 1,
            "withCredentials": false
        },
        "changed": true,
        "failed": false,
        "id": 2,
        "msg": "Datasource prometheus updated Datasource updated",
        "name": "prometheus"
    }
}
```

**Comment by ecksun** [comment]
I'm still seeing this issue with ansible 2.9.13.

**Comment by mario-pranjic** [comment]
I just opened a bug (autoclosed on main Ansible) :)
https://github.com/ansible/ansible/issues/71724

Same issue.

**Comment by hal58th** [comment]
This issue is 5 years old and going strong 💪

**Comment by rndmh3ro** [comment]
> This issue is 5 years old and going strong 💪

Did you actually check if this is still a problem or are you just here to leave a comment?

**Comment by hal58th** [comment]
@rndmh3ro This issue may have been fixed in the past but this is my current issue.

When I run the playbook with `--diff`, it shows that the "apiVersion" is removed, which is not an option I can set or remove.

```
TASK [Add the prometheus data source]
--- before
+++ after
@@ -1,5 +1,4 @@
     access: proxy
-    apiVersion: ''
     basicAuth: false
     database: ''
     isDefault: true

changed: [host01.redacted] => 
    attempts: 1
    changed: true
    datasource:
        access: proxy
        apiVersion: ''
        basicAuth: false
        basicAuthUser: MYUSER
        database: ''
        id: 1
        isDefault: true
        jsonData:
            tlsAuth: false
            tlsAuthWithCACert: false
        name: prometheus
        orgId: 1
        readOnly: false
        secureJsonFields:
            basicAuthPassword: true
        type: prometheus
        typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
        uid: MYUID
        url: https://prometheus.redacted
        user: ''
        version: 1
        withCredentials: false
    msg: Datasource prometheus updated
```

This is my task:
```
- name: Add the prometheus data source
  community.grafana.grafana_datasource:
    access: proxy
    name: prometheus
    ds_type: prometheus
    ds_url: "https://prometheus.redacted"
    is_default: true
    org_id: 1
    state: present
    url: "https://grafana.redacted"
    url_username: "MY_USERNAME"
    url_password: "MY_PASSWORD"
    validate_certs: false
    uid: MYUID
```
