### ISSUE TITLE
Unable to create Elasticsearch datasource with es_version: 70

### ISSUE THREAD

**Issue by thadeej** [ansible-collections/community.grafana#129]
##### SUMMARY

Error: ```FAILED! => {"changed": false, "msg": "value of es_version must be one of: 2, 5, 56, got: 70"}```

Appears to be supported:
```python
/plugins/modules/grafana_datasource.py
es_version:
    description:
    - Elasticsearch version (for C(ds_type = elasticsearch) only)
    - Version 56 is for elasticsearch 5.6+ where you can specify the C(max_concurrent_shard_requests)
      option.
    choices:
    - 2
    - 5
    - 56
    - 60
    - 70
    default: 5
    type: int
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`grafana_datasource`

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/$home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### CONFIGURATION

```paste below
NO CHANGES
verified COLLECTION_PATH
verified collection installed to path
```

##### OS / ENVIRONMENT

Tested on Mac OS 10.15.5 as well as Linux 20.04.1

##### STEPS TO REPRODUCE

Run playbook which calls for:
```yaml
collections:
    - community.grafana
```

when it attempts to process the datasource.yml, the above error is produced

```yaml
datasource.yml
- name: Create EC Certificates datasource
  grafana_datasource:
    name: "EC - certificates"
    grafana_url: "{{ grafana_url }}"
    grafana_user: "{{ grafana_admin }}"
    grafana_password: "{{ grafana_pass }}"
    org_id: "1"
    ds_type: "elasticsearch"
    ds_url: "{{ elastic_url }}"
    database: "{{ index_id }}"
    basic_auth_user: "{{ elastic_user }}"
    basic_auth_password: "{{ elastic_pass }}"
    time_field: "@timestamp"
    time_interval: "1m"
    es_version: 70
    max_concurrent_shard_requests: 5

```

##### EXPECTED RESULTS

Create the datasource with Elasticsearch version 7.0+

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "msg": "value of es_version must be one of: 2, 5, 56, got: 70"}

```

**Comment by thadeej** [comment]
I've found my error.
My error was in an assumption that I could call the collection in the playbook and not define it further down in the tasks.
When I changed my datasources.yml to call community.grafana.grafana.datasources, it works.
```yaml
datasource.yml
- name: Create EC Certificates datasource
  community.grafana.grafana_datasource:
```
