### ISSUE TITLE
support module group defaults

### ISSUE THREAD

**Issue by ikke-t** [ansible-collections/community.grafana#136]
##### SUMMARY

As a user I want avoid repeating same parameters to module tasks in playbooks using [module group defaults](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
All components.

##### ADDITIONAL INFORMATION

I have long list of tasks for datasources, dashboards, users... and I avoid repeating the same parameters by using module defaults.

```yaml
  collections:
    - community.grafana

  module_defaults:
    grafana_datasource:
      url: "http://localhost:3000"
      url_username: "admin"
      url_password: "foo"
      org_id: "1"
      ds_url: "http://influxdb.localnet:8086"
      user: 'foo'
      password: 'foo'
      time_interval: ">10s"
    grafana_dashboard:
      grafana_url: "http://localhost:3000"
      url_username: "admin"
      url_password: "foo"
      org_id: "1"
    grafana_user:
      grafana_url: "http://localhost:3000"
      url_username: "admin"
      url_password: "foo"

tasks:
    - name: Ensure Influxdb datasource exists.
      grafana_datasource:
        name: "influxdb"
        ds_type: "influxdb"
        database: "sensorit"

    - name: Ensure katkaisimet datasource exists.
      grafana_datasource:
        name: "katkaisimet"
        ds_type: "influxdb"
        database: "katkaisimet"

....
```

Now if there was group defaults, I could avoid repeating even further, putting all variables under one group which then would apply to all modules at once:

```yaml
  collections:
    - community.grafana

  module_defaults:
    group/grafana:
      url: "http://localhost:3000"
      url_username: "admin"
      url_password: "foo"
```

FYI, e.g. k8s modules implement this.
