### ISSUE TITLE
is_admin does not work for user

### ISSUE THREAD

**Issue by ikke-t** [ansible-collections/community.grafana#142]
##### SUMMARY

I used this module, and noticed is_admin: true -types of users end up being viewers only in grafana.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

grafana_user.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = /home/itengval/src/ansible-test/ansible.cfg
  configured module search path = ['/home/itengval/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/itengval/src/ansible-test/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/itengval/src/ansible-test/ansible.cfg) = ['timer']
DEFAULT_ROLES_PATH(/home/itengval/src/ansible-test/ansible.cfg) = ['/home/itengval/src/ansible-test/roles']
HOST_KEY_CHECKING(/home/itengval/src/ansible-test/ansible.cfg) = False

```

##### OS / ENVIRONMENT

RHEL 8.3

##### STEPS TO REPRODUCE

All the users on the list become viewers, not admins.

```yaml
---
grafana_admins:
  - login: test-admin
    name: 'Test Admin'
    email: 'test.admin@localhost.localdomain'
    password: 'test'
grafana_users:
  - login: test-user
    name: 'Test User'
    email: 'test.user@localhost.localdomain'
    password: 'test'


---
- name: Ensure admins
  tags: push
  community.grafana.grafana_user:
    url: "{{ grafana_url }}"
    url_username: "{{ grafana_admin }}"
    url_password: "{{ grafana_admin_password }}"
    name: "{{ item.name }}"
    email: "{{ item.email }}"
    login: "{{ item.login }}"
    password: "{{ item.password }}"
    is_admin: true
    state: present
  no_log: true
  loop: "{{ grafana_admins }}"

- name: Ensure users
  tags: push
  community.grafana.grafana_user:
    grafana_url: "{{ grafana_url }}"
    url_username: "{{ grafana_admin }}"
    url_password: "{{ grafana_admin_password }}"
    name: "{{ item.name }}"
    email: "{{ item.email }}"
    login: "{{ item.login }}"
    password: "{{ item.password }}"
    is_admin: false
    state: present
  no_log: true
  loop: "{{ grafana_users }}"

```

##### EXPECTED RESULTS

is_admin to make user and admin

##### ACTUAL RESULTS

all become viewers.
