### ISSUE TITLE
Can't set datasource 'Access' to 'Server (default)'

### ISSUE THREAD

**Issue by PC-Admin** [ansible-collections/community.grafana#143]
##### SUMMARY

It is not possible to set a datasources 'Access' field to 'Server (default)' using ansible:
```
- name: create prometheus datasource
  community.grafana.grafana_datasource:
    name: local_prometheus
    access: direct
    ds_type: prometheus
    ds_url: 'http://127.0.0.1:9090'
    access: direct
    tls_skip_verify: true
    url: "https://{{ grafana_url }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
```

Set the 'access' variable here to 'direct' or 'proxy', it makes no difference, in the GUI the datasources 'Access' field will always be set to 'Browser'.

![Graphana-trouble](https://user-images.githubusercontent.com/29645145/103729152-b4587580-501a-11eb-9de0-a28d74a97264.png)

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.6
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/location/ansible.cfg) = True
RETRY_FILES_ENABLED(/location/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian 10 for both the controller and the target.

##### STEPS TO REPRODUCE

```
Just use the above code.
```

##### EXPECTED RESULTS

I expected there to be some way to set this value to 'Server (default)' using ansible.

##### ACTUAL RESULTS

```paste below

```
