### ISSUE TITLE
Imposible to pass TLS CA certificate for self signed certificates

### ISSUE THREAD

**Issue by DAGorchakov** [ansible-collections/community.grafana#155]
##### SUMMARY

In Ansible play I try to pass TLS CA certificate (in Grafana GUI it is 'With CA cert') to connect to Loki (behind NGINX with TLS and basic auth), but it is looks like I can only connect with mTLS or skip TLS verify?

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
community.grafana:1.2.0
```

##### CONFIGURATION

```paste below
[defaults]
callback_whitelist = profile_tasks
remote_tmp     = ~/.ansible/tmp
```

##### OS / ENVIRONMENT

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-1160.6.1.el7.x86_64

##### STEPS TO REPRODUCE

```yaml
- name: Create Loki datasource
  community.grafana.grafana_datasource:
    name: "Loki"
    grafana_url: "https://localhost:3000"
    ds_type: "loki"
    ds_url: "https://{{ hostvars[inventory_hostname]['groups']['loki'][0] }}:3100"
    basic_auth_user: "{{ loki_basic_auth_user }}"
    basic_auth_password: "{{ loki_basic_auth_password }}"
    tls_ca_cert: "-----BEGIN CERTIFICATE-----MIIDRTCCAi2gAwIBA.....ucBXA==-----END CERTIFICATE-----"
    validate_certs: False
    is_default: no
```

##### EXPECTED RESULTS

I look into Grafana datasources and want to see this:
![image](https://user-images.githubusercontent.com/17656075/110767498-5ee15480-8267-11eb-974c-884143daa2c8.png)

##### ACTUAL RESULTS

But actually I see that CA is not used and configured:
![image](https://user-images.githubusercontent.com/17656075/110767741-a2d45980-8267-11eb-9504-9627280425a6.png)

```paste below
changed: [vm-12.vm.com] => {
    "changed": true,
    "datasource": {
        "access": "proxy",
        "basicAuth": true,
        "basicAuthPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "basicAuthUser": "user",
        "database": "",
        "id": 18,
        "isDefault": false,
        "jsonData": {
            "tlsAuth": false,
            "tlsAuthWithCACert": false
        },
        "name": "Loki",
        "orgId": 1,
        "password": "",
        "readOnly": false,
        "secureJsonFields": {
            "tlsCACert": true
        },
        "type": "loki",
        "typeLogoUrl": "",
        "uid": "AV48k-8Mk",
        "url": "https://loki-01.vm.com:3100",
        "user": "",
        "version": 1,
        "withCredentials": false
    },
    "diff": {
        "after": {
            "access": "proxy",
            "basicAuth": true,
            "basicAuthPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "basicAuthUser": "user",
            "database": "",
            "isDefault": false,
            "jsonData": {
                "tlsAuth": false,
                "tlsAuthWithCACert": false
            },
            "name": "Loki",
            "orgId": 1,
            "password": "",
            "type": "loki",
            "url": "https://loki-01.vm.com:3100",
            "user": "",
            "withCredentials": false
        },
        "before": {
            "access": "proxy",
            "basicAuth": true,
            "basicAuthPassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "basicAuthUser": "user",
            "database": "",
            "isDefault": false,
            "jsonData": {
                "tlsAuth": false,
                "tlsAuthWithCACert": false
            },
            "name": "Loki",
            "orgId": 1,
            "password": "",
            "type": "loki",
            "uid": "AV48k-8Mk",
            "url": "https://loki-01.vm.com:3100",
            "user": "",
            "withCredentials": false
        }
    },
    "invocation": {
        "module_args": {
            "access": "proxy",
            "additional_json_data": {
                "tlsAuth": false,
                "tlsAuthWithCACert": false
            },
            "additional_secure_json_data": {
                "tlsCACert": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "aws_access_key": "",
            "aws_assume_role_arn": "",
            "aws_auth_type": "keys",
            "aws_credentials_profile": "",
            "aws_custom_metrics_namespaces": null,
            "aws_default_region": "us-east-1",
            "aws_secret_key": "",
            "basic_auth_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "basic_auth_user": "user",
            "client_cert": null,
            "client_key": null,
            "database": "",
            "ds_type": "loki",
            "ds_url": "https://loki-01.vm.com:3100",
            "enforce_secure_data": false,
            "es_version": 5,
            "grafana_api_key": null,
            "grafana_url": "https://localhost:3000",
            "interval": "",
            "is_default": false,
            "max_concurrent_shard_requests": 256,
            "name": "Loki",
            "org_id": 1,
            "password": "",
            "sslmode": "disable",
            "state": "present",
            "time_field": "@timestamp",
            "time_interval": null,
            "tls_ca_cert": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tls_client_cert": null,
            "tls_client_key": null,
            "tls_skip_verify": false,
            "trends": false,
            "tsdb_resolution": "second",
            "tsdb_version": 1,
            "url": "https://localhost:3000",
            "url_password": "admin",
            "url_username": "admin",
            "use_proxy": true,
            "user": "",
            "validate_certs": false,
            "with_credentials": false,
            "zabbix_password": null,
            "zabbix_user": null
        }
    },
    "msg": "Datasource Loki updated"
}
```

**Comment by DAGorchakov** [comment]
if I use Grafana API and POST this:
```json
curl -k -u admin:admin -d '{
	"name": "Loki",
	"type": "loki",
	"access": "proxy",
	"url": "https://loki-01.vm.com:3100",
	"basicAuth": true,
	"basicAuthUser": "user",
	"basicAuthPassword": "123",
	"isDefault": false,
	"jsonData": {
		"tlsAuthWithCACert": true
	},
	"secureJsonData": {
		"tlsCACert": "-----BEGIN CERTIFICATE-----\nMyCert==\n-----END CERTIFICATE-----\n"
	}
}' -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST https://vm-12.vm.com:3000/api/datasources
```
it works perfect:
![image](https://user-images.githubusercontent.com/17656075/110922876-4dfd1580-8331-11eb-82d6-56e7f6bebe8d.png)

BUT if I use ansible: 
```yaml
- name: Create Loki datasource
  community.grafana.grafana_datasource:
    name: "Loki"
    grafana_url: "https://localhost:3000"
    ds_type: "loki"
    ds_url: "https://{{ hostvars[inventory_hostname]['groups']['loki'][0] }}:3100"
    basic_auth_user: "{{ loki_basic_auth_user }}"
    basic_auth_password: "{{ loki_basic_auth_password }}"
    additional_json_data: 
      tlsAuthWithCACert: "true"
    additional_secure_json_data:
      tlsCACert: "-----BEGIN CERTIFICATE-----\nMyCert\n-----END CERTIFICATE-----\n"
    validate_certs: False
    is_default: no
```
I have to turn on `With CA Cert`
![image](https://user-images.githubusercontent.com/17656075/110923164-a502ea80-8331-11eb-9d9e-855680b6fdba.png)
Is it correct?
