### ISSUE TITLE
grafana_datasource: Data source removal requires ds_type and ds_url

### ISSUE THREAD

**Issue by rsirny** [ansible-collections/community.grafana#170]
##### SUMMARY

Data source removal unnecessarily requires ds_type and ds_url parameters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_datasource

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /mnt/c/myrepo/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 33; Grafana 7.5.4

##### STEPS TO REPRODUCE

Run the following playbook. It fails with message `missing required arguments: ds_url, ds_type`.

```yaml
---
- hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - name: Remove datasource
    community.grafana.grafana_datasource:
      grafana_url: "{{ grafana_base_uri }}"
      grafana_user: "{{ grafana_admin_user }}"
      grafana_password: "{{ grafana_admin_password }}"
      name: "DS_to_remove"
      state: absent
```

##### EXPECTED RESULTS

Since datasource names are unique (e.g. see [Grafana API Delete data source by name method](https://grafana.com/docs/grafana/latest/http_api/data_source/#delete-an-existing-data-source-by-name)), I would expect that only name is necessary in removal scenario.

##### ACTUAL RESULTS

Playbook fails due to ds_url and ds_type missing.

```paste below
PLAY [localhost] ****************************************************************************************************************************************************************************************************

TASK [Remove datasource] ********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: ds_url, ds_type"}

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
