### ISSUE TITLE
Configure datasource always wants to remove it's UID

### ISSUE THREAD

**Issue by Sebi94nbg** [ansible-collections/community.grafana#176]
##### SUMMARY

I've set up a Grafana installation using Ansible and configured it (eg. datasources, dashboards, ...) manually. Now, I'm working on the datasource configuration in Ansible and it works nearly as expected. The only problem is, that it ALWAYS wants to remove the UID from the existing resources, but in fact it doesn't change/remove those - they stay untouched / the same.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.grafana.grafana_datasource`

##### ANSIBLE VERSION

```paste below
ansible 2.9.17
  config file = /home/skraetzig/Documents/Git/infrastructure/ansible.cfg
  configured module search path = ['/home/skraetzig/Documents/Git/infrastructure/ansible/library']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

##### COLLECTION VERSION

```paste below
❯ cat ansible-requirements.yml
---
collections:
- name: community.grafana
  version: 1.2.1
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_NOCOWS(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = True
ANSIBLE_SSH_ARGS(env: ANSIBLE_SSH_ARGS) = -C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/home/skraetzig/Documents/Git/infrastructure/generated/known_hosts
ANY_ERRORS_FATAL(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = True
COLLECTIONS_PATHS(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = ['/usr/share/ansible/third-party/collections']
DEFAULT_FILTER_PLUGIN_PATH(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = ['/home/skraetzig/Documents/Git/infrastructure/ansible/filter_plugins']
DEFAULT_FORKS(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = 50
DEFAULT_LOCAL_TMP(env: ANSIBLE_LOCAL_TEMP) = /tmp/ansible-local-1kpuuoik7
DEFAULT_MODULE_PATH(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = ['/home/skraetzig/Documents/Git/infrastructure/ansible/library']
DEFAULT_REMOTE_USER(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = deploy
DEFAULT_ROLES_PATH(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = ['/home/skraetzig/Documents/Git/infrastructure/ansible/roles', '/home/skraetzig/Documents/Git/infr
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = default
DIFF_ALWAYS(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = True
INTERPRETER_PYTHON(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = /usr/bin/python3
MAX_FILE_SIZE_FOR_DIFF(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = 1044480
RETRY_FILES_ENABLED(/home/skraetzig/Documents/Git/infrastructure/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

```
Grafana v8.0.5 (previous used version until the update on 2021-08-25)
Grafana v8.1.2 (using this version since the update on  2021-08-25)
``` 

##### STEPS TO REPRODUCE
`roles/grafana/tasks/main.yml`:
```yaml
---
- name: configure datasources
  community.grafana.grafana_datasource:
    grafana_url: "{{ grafana_full_root_url }}"
    name: "{{ item.name }}"
    is_default: "{{ item.is_default | default('no') }}"
    ds_type: "{{ item.ds_type }}"
    ds_url: "{{ item.ds_url }}"
    access: proxy
    state: present
  with_items: "{{ grafana_datasources.present | list }}"
```

`inventory/prod/group_vars/grafana/grafana.yml`:
```yaml
grafana_datasources:
  present:
    - name: Prometheus
      is_default: yes
      ds_type: prometheus
      ds_url: http://prometheus.production.example.com
    - name: Prometheus AlertManager
      ds_type: camptocamp-prometheus-alertmanager-datasource
      ds_url: http://alertmanager.production.example.com
  absent: []
```

```shell
❯ ANSIBLE_STDOUT_CALLBACK=actionable ansible-playbook -i inventory/prod/ playbooks/configure-grafana.yml --tags grafana
[...]

TASK [grafana : configure datasources] ******************************************************************************************************************************************
--- before
+++ after
@@ -11,7 +11,6 @@
     "orgId": 1,
     "password": "",
     "type": "prometheus",
-    "uid": "w_SD0On7z",
     "url": "http://prometheus.production.example.com",
     "user": "",
     "withCredentials": false

changed: [prometheus-01-01.host.production.example.com] => (item={'name': 'Prometheus', 'is_default': True, 'ds_type': 'prometheus', 'ds_url': 'http://prometheus.production.example.com'})
--- before
+++ after
@@ -11,7 +11,6 @@
     "orgId": 1,
     "password": "",
     "type": "camptocamp-prometheus-alertmanager-datasource",
-    "uid": "5KZKCjk7z",
     "url": "http://alertmanager.production.example.com",
     "user": "",
     "withCredentials": false

changed: [prometheus-01-01.host.production.example.com] => (item={'name': 'Prometheus AlertManager', 'ds_type': 'camptocamp-prometheus-alertmanager-datasource', 'ds_url': 'http://alertmanager.production.example.com'})

[...]
```

##### EXPECTED RESULTS
The `uid` should never be removed or shown as "removed".

##### ACTUAL RESULTS
See above. Adding `enforce_secure_data: true` doesn't change the behaviour.
