### ISSUE TITLE
Prometheus data source basic_auth_password not set correctly

### ISSUE THREAD

**Issue by nislab-hslu** [ansible-collections/community.grafana#204]
##### SUMMARY

When adding a prometheus datasource using basic_auth_user and basic_auth_password, a password is set but it does not work.
The Grafana GUI shows `Error reading Prometheus: client_error: client error: 401` when pressing `Save & Test` on the prometheus datasource added by ansible.

After entering the password manually via Grafana GUI the datasource works as expected.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = /workspaces/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansiblevenv/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/ansiblevenv/bin/ansible
  python version = 3.10.2 (main, Jan 29 2022, 02:41:17) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.grafana 1.3.0
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/workspaces/ansible/ansible.cfg) = 100
DEFAULT_HOST_LIST(/workspaces/ansible/ansible.cfg) = ['/workspaces/ansible/hosts.yml']
DEFAULT_ROLES_PATH(/workspaces/ansible/ansible.cfg) = ['/workspaces/ansible/roles']
HOST_KEY_CHECKING(/workspaces/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/workspaces/ansible/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

```
$ /usr/sbin/grafana-server -v
Version 8.3.4 (commit: a551d74b11, branch: HEAD)
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

```
$ uname -a
Linux c2-services 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```yaml
- name: 'add prometheus datasource'
  hosts: 'localhost'
  gather_facts: true

  tasks:
    - name: 'add prometheus datasource'
      community.grafana.grafana_datasource:
        name: 'Prometheus'
        org_id: '1'
        ds_type: 'prometheus'
        ds_url: 'http://localhost:9090'
        basic_auth_user: 'prometheus'
        basic_auth_password: 'prometheus'
        state: 'present'
        is_default: true
        grafana_url: 'http://localhost:3000'
        grafana_user: 'admin'
        grafana_password: 'grafana'
```

##### EXPECTED RESULTS

The prometheus data source should be configured correctly, including basic_auth_password.

##### ACTUAL RESULTS

The prometheus data source is not configured correctly. No data can be read from prometheus.
The basic auth password is set (Grafana GUI displays password as `configured`) but when pressing `Test & Save` the GUI displays `Error reading Prometheus: client_error: client error: 401` pointing to the basic auth password not being correct (after manually entering the password it works).

```paste below

```
