### ISSUE TITLE
Cloudwatch Datasource - Unable to set AWS SDK Default

### ISSUE THREAD

**Issue by jseiser** [ansible-collections/community.grafana#205]
##### SUMMARY

There is no way to configure a cloudwatch datasource to use the 'AWS SDK Default'  as its 'Authentication Provider'
An EC2 Instance, that has an IAM role attached which would grant access to the Cloudwatch resources should not require using AWS keys, or assuming roles etc.  This works if you go in and set it by hand.

![Screen Shot 2022-02-16 at 2 17 21 PM](https://user-images.githubusercontent.com/4855527/154339741-828443e0-4137-4591-896a-036fbafeb612.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.grafana.grafana_datasource

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/Users/justinseiser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/justinseiser/.local/pipx/venvs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/justinseiser/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/justinseiser/.local/bin/ansible
  python version = 3.9.6 (default, Jul  9 2021, 20:14:32) [Clang 12.0.5 (clang-1205.0.22.11)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
collections:
  - community.grafana
```

##### STEPS TO REPRODUCE
Create AWS instance with an IAM role that contains policies which grant access to Cloudwatch.

```yaml
    - name: AWS Cloudwatch datasource
      community.grafana.grafana_datasource:
        name: cloudwatch
        grafana_url: https://localhost:3000
        grafana_user: admin
        grafana_password: "{{ grafana.admin_password }}"
        ds_type: cloudwatch
        ds_url: "http://monitoring.{{ lookup('env', 'AWS_REGION') }}.amazonaws.com"
        validate_certs: no
```

##### EXPECTED RESULTS
Cloudwatch would be configured with the `AWS SDK Default`

##### ACTUAL RESULTS
It defaults to keys.  It does not even offer "AWS SDK Default"

EDIT.

I see if I set it to 'credentials' you get a warning.

```
As of grafana 7.3 authentication type "credentials" should be used only for shared file credentials. If you don't have a credentials file, switch to the default SDK provider for extracting credentials from environment variables or IAM roles
```

**Comment by jseiser** [comment]
Example of what works when returned via curl

```
{
  "id": 5,
  "uid": "UTN-lGBnk",
  "orgId": 1,
  "name": "cloudwatch",
  "type": "cloudwatch",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://monitoring.us-gov-west-1.amazonaws.com",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": false,
  "jsonData": {
    "authType": "default",
    "defaultRegion": "us-gov-west-1",
    "tlsAuth": false,
    "tlsAuthWithCACert": false
  },
  "secureJsonFields": {},
  "version": 2,
  "readOnly": false
}
```

**Comment by jseiser** [comment]
If you define this.

```
    - name: AWS Cloudwatch datasource
      community.grafana.grafana_datasource:
        name: cloudwatch
        grafana_url: https://localhost:3000
        grafana_user: admin
        grafana_password: "{{ grafana.admin_password }}"
        additional_json_data:
          authType: "default"
          defaultRegion: "us-gov-west-1"
        ds_type: cloudwatch
        ds_url: "http://monitoring.{{ lookup('env', 'AWS_REGION') }}.amazonaws.com"
        validate_certs: no
```

The JSON stuff gets overwrote.

```
        "jsonData": {
            "authType": "keys",
            "defaultRegion": "us-east-1",
            "tlsAuth": false,
            "tlsAuthWithCACert": false
        },
```
