### ISSUE TITLE
Grafana dashboard should return dashboard id too

### ISSUE THREAD

**Issue by Lusitaniae** [ansible-collections/community.grafana#235]
https://docs.ansible.com/ansible/latest/collections/community/grafana/grafana_dashboard_module.html

As documented here only the uid of the referenced dashboard is returned, however to interact with Grafana's Dashboad permissions API we'd need to use the ID instead of UID (the APIs seem to be inconsistent, the folder permissions API requires uid?)

https://grafana.com/docs/grafana/latest/http_api/dashboard_permissions/#update-permissions-for-a-dashboard

Work around using ansible uri to interact with API
```
- name: Import Grafana dashboard
  community.grafana.grafana_dashboard:
      ... args list
  register: dashboard

- name: Get dashboard id
  uri:
    url: "{{ grafana_url }}/api/dashboards/uid/{{ dashboard.results[0].uid }}"
    return_content: yes
    headers:
      Authorization: "Basic {{ (grafana_user + ':' + grafana_pass_decoded )| b64encode }}"
  register: dashboard_id

- name: Set dashboard permissions
  uri:
    url: "{{ grafana_url }}/api/dashboards/id/{{ dashboard_id.json.dashboard.id }}/permissions"
    method: POST
    body: | # 1 - viewer | 2 - editor # teamId requires int here, otherwise returns 400
        {"items": [
            {"teamId": {{ team.team.id | int }}, "permission": 1}
        ]}
    body_format: json
    return_content: yes
    headers:
      Authorization: "Basic {{ (grafana_user + ':' + grafana_pass_decoded )| b64encode }}"
  register: folder_perms
```
