### ISSUE TITLE
error on grafana 9.0

### ISSUE THREAD

**Issue by miettal** [ansible-collections/community.grafana#248]
##### SUMMARY
Datasource module cause error of "KeyError: 'password'".

It seems grafana droped password and basicAuthPassword attributes of datasource object from 9.0.0.

> Removes support for storing/using datasource password and basicAuthPassword unencrypted which was [deprecated in Grafana v8.1.0](https://grafana.com/docs/grafana/latest/installation/upgrading/#use-of-unencrypted-passwords-for-data-sources-no-longer-supported).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
datasource module

##### ANSIBLE VERSION
2.12.5

##### COLLECTION VERSION
1.4

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
      - name: xxx
        grafana_datasource:
          name: "xxx"
          grafana_url: "http://localhost:3000"
          grafana_user: "xxx"
          grafana_password: "xxx"
          org_id: "1"
          ds_type: "influxdb"
          ds_url: "http://localhost:8086"
          database: "xxx"
          user: 'xxx'
          password: 'xxx'
```

##### EXPECTED RESULTS

success

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'password'
fatal: [xxx]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1655391494.499609-53346-58637564971731/AnsiballZ_grafana_datasource.py\", line 107,
in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1655391494.499609-53346-58637564971731/AnsiballZ_grafana_datasource.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/u
buntu/.ansible/tmp/ansible-tmp-1655391494.499609-53346-58637564971731/AnsiballZ_grafana_datasource.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.grafana.plugins.modules.grafana_datasource', init_globals=dict(_module_fqn=
'ansible_collections.community.grafana.plugins.modules.grafana_datasource', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.
8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_grafana_datasource_payload_7uu8wyxo/ansible_grafana_data
source_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_datasource.py\", line 769, in <module>\r\n  File \"/tmp/ansible_grafana_datasource_payload_7uu8wyxo/ansible_grafana_datasource_payload.zip/ansible_collections/community/grafana/plugins/modu
les/grafana_datasource.py\", line 752, in main\r\n  File \"/tmp/ansible_grafana_datasource_payload_7uu8wyxo/ansible_grafana_datasource_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_datasource.py\", line 477, in compare_datasources\r\nKeyError
: 'password'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

https://github.com/ansible-collections/community.grafana/blob/main/plugins/modules/grafana_datasource.py#L504
