### ISSUE TITLE
Pretty printed dashboard export

### ISSUE THREAD

**Issue by kongslund** [ansible-collections/community.grafana#257]
##### SUMMARY
Support exporting a dashboard with pretty printed JSON so that it becomes easier to compare changes with the previous version.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
grafana_dashboard

##### ADDITIONAL INFORMATION

Often when I export dashboards, I have a need to compare them with previous versions.

I use the `grafana_dashboard` module for exporting the dashboards. The current JSON output is compact and not so easy to compare in a diff, so I have an additional step of pretty printing each exported dashboard file.

It would be more convenient for this use case if `grafana_dashboard` supports pretty printing out of the box.

I see two possible approaches to introducing this:

A) Change `grafana_dashboard` to always export dashboards as pretty printed. I prefer this one.
B) Add a module option `export_style` which determines if the resulting JSON should be compact as today or pretty printed. The two allowed values would be `compact` (default) and `pretty`.

Example:
```yaml
- name: Export a pretty dashboard
  grafana_dashboard:
    grafana_url: "..."
    grafana_user: "..."
    grafana_password: "..."
    state: export
    export_style: pretty
    path: /a/pretty/dashboard.json
    overwrite: true
    uid: "{{ dashboard_uid }}"
```

Would there be interest if I create a PR for either approach A or B?
