### ISSUE TITLE
Change password for default user (admin/admin)

### ISSUE THREAD

**Issue by grzanka** [ansible-collections/community.grafana#281]
##### SUMMARY
My request is related to discussion in the following issue: https://github.com/ansible-collections/community.grafana/issues/142
I was trying to secure a freshly created grafana instance. Doing this using web interface is simple: one needs to change the default password for admin account. At first login after typing admin/admin credentials you are asked to change the password to secure one.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I suspect its user management module.

##### ADDITIONAL INFORMATION
I would like to be able to secure fresh graphana instance.
There are couple of ways of doing so.

First one, which seems not to be working, is to change password of default user (admin/admin):

I've tried it using following playbook:
```yaml
  - name: Setup grafana instance
    hosts: all_hosts
    remote_user: opc
    collections:
      - community.grafana
    vars:
      - grafana_root_password: "{{ lookup('ansible.builtin.env', 'GRAFANA_ROOT_PASSWORD') }}"
  
    module_defaults:
      group/community.grafana.grafana:
        url: "http://localhost:3000"

    tasks:
      - name: Create new admin (using admin/admin credentials)
        grafana_user:
          url_username: admin
          url_password: admin
          name: "Aministrator"
          email: admin@{{ ansible_hostname }}
          login: root
          password: '{{ grafana_root_password }}'
          is_admin: true
          state: present
        register: result
      - debug:
          msg: "{{ result }}"

      - name: Change password for default admin
        grafana_user:
          url_username: admin
          url_password: admin
          name: "Default aministrator"
          email: admin@{{ ansible_hostname }}
          login: admin
          is_admin: true
          password: '{{ grafana_root_password }}'
          state: present
        register: result
      - debug:
          msg: "{{ result }}"
```

and running the command:
```
GRAFANA_ROOT_PASSWORD=xxxx ansible-playbook fast_grafana.yaml -i inventory.oci.yml
```

but this failed with:
```
(venv) ubuntu@shieldhitrunner:~/workspace/$ GRAFANA_ROOT_PASSWORD=XXX ansible-playbook fast_grafana.yaml -i inventory.oci.yml 
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [Setup grafana instance] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
[WARNING]: Platform linux on host 130.61.85.231 is using the discovered Python interpreter at /usr/bin/python3.6, but future installation of another Python interpreter could change the meaning of that path.
See https://docs.ansible.com/ansible-core/2.13/reference_appendices/interpreter_discovery.html for more information.
ok: [130.61.85.231]

TASK [Create new admin (using admin/admin credentials)] ********************************************************************************************************************************************************
ok: [130.61.85.231]

TASK [debug] ***************************************************************************************************************************************************************************************************
ok: [130.61.85.231] => {
    "msg": {
        "changed": false,
        "failed": false,
        "user": {
            "authLabels": null,
            "avatarUrl": "",
            "createdAt": "2022-10-07T20:10:00Z",
            "email": "********@th",
            "id": 2,
            "isDisabled": false,
            "isExternal": false,
            "isGrafanaAdmin": true,
            "login": "root",
            "name": "Aministrator",
            "orgId": 1,
            "theme": "",
            "updatedAt": "2022-10-07T20:10:00Z"
        }
    }
}

TASK [Change password for default admin] ***********************************************************************************************************************************************************************
fatal: [130.61.85.231]: FAILED! => {"changed": false, "msg": "Permission Denied"}
```
