### ISSUE TITLE
dingding_message_type: The error was: TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by devbean** [ansible-collections/community.grafana#284]
##### SUMMARY

Use `dingding_message_type` of `grafana_notification_channel` in storybook will cause error: The error was: TypeError: unhashable type: 'list'.

After reading the code I found that might because of [this code line](https://github.com/ansible-collections/community.grafana/blob/main/plugins/modules/grafana_notification_channel.py#L440). (PS: I'm not familiar with Python though)

Since `dingding_message_type` should be string only so I think it is OK to change `dingding_message_type` type to string.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

grafana_notification_channel

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.4]
  config file = /home/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/rh/rh-python38/root/usr/local/bin/ansible
  python version = 3.8.13 (default, Aug 16 2022, 12:16:29) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.grafana 1.5.2
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Create dingding notification channel
  community.grafana.grafana_notification_channel:
    uid: dingding
    name: dingding
    type: dingding
    grafana_url: http://localhost:3000
    grafana_user: admin
    grafana_password: admin
    reminder_frequency: 15m
    is_default: true
    dingding_message_type:
      - action_card
    dingding_url: '{{ user.grafana.dingding_send_url }}'
    include_image: false
    pagerduty_severity:
      - critical
    webhook_http_method:
      - POST
    pagerduty_auto_resolve: true
```

##### ACTUAL RESULTS

```paste below

```
