### ISSUE TITLE
Grafana plugins parameter missing

### ISSUE THREAD

**Issue by miksonx** [ansible-collections/community.grafana#289]
##### SUMMARY
Validate certs option available in code 
https://github.com/ansible-collections/community.grafana/blob/main/plugins/modules/grafana_plugin.py#L119

but not available as parameter
https://github.com/ansible-collections/community.grafana/blob/main/plugins/modules/grafana_plugin.py#L234

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_plugin

##### ANSIBLE VERSION

```paste below
2.12.2
```

##### COLLECTION VERSION

```paste below
Colletion  Version
----------------------
community.general 1.3.2

Colletion  Version
----------------------
community.general 1.5.3

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RH8

##### STEPS TO REPRODUCE

```yaml
- name: Install plugins
  community.grafana.grafana_plugin:
    name: alexanderzobnin-zabbix-app
    version: 4.2.10
    state: present
    validate_certs: False
```

##### EXPECTED RESULTS

No error and command to be executed with --insecure

##### ACTUAL RESULTS

"msg": "Unsupported parameters for (community.grafana.grafana_plugin) module: validate_certs. Supported parameters include: grafana_plugins_dir, state, grafana_plugin_url, version, grafana_repo, name."

```paste below

```
