### ISSUE TITLE
[datasource] Missing serverName when using mTLS for Loki backend

### ISSUE THREAD

**Issue by TiJof** [ansible-collections/community.grafana#389]
##### SUMMARY
When using mTLS in for a Loki datasource, the serverName is missing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.grafana.grafana_datasource

##### ANSIBLE VERSION
```
ansible [core 2.17.2]
  config file = /root/loki-logsecu/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] (/root/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True

```

##### COLLECTION VERSION
```
community.grafana                        1.9.1  
grafana.grafana                          5.3.0  
```

##### CONFIGURATION

```
CACHE_PLUGIN(/root/loki-logsecu/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/root/loki-logsecu/ansible.cfg) = ./ansible-cache
CACHE_PLUGIN_TIMEOUT(/root/loki-logsecu/ansible.cfg) = 3600
CALLBACKS_ENABLED(/root/loki-logsecu/ansible.cfg) = ['ansible.posix.timer', 'ansible.posix.profile_tasks', 'ansible.posix.profile_roles']
CONFIG_FILE() = /root/loki-logsecu/ansible.cfg
DEFAULT_GATHERING(/root/loki-logsecu/ansible.cfg) = smart
DEFAULT_TIMEOUT(/root/loki-logsecu/ansible.cfg) = 30
INTERPRETER_PYTHON(/root/loki-logsecu/ansible.cfg) = auto
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/root/loki-logsecu/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Debian 12
Grafana 11.1.3

##### STEPS TO REPRODUCE

```yaml
- name: Create data source
  community.grafana.grafana_datasource:
    name: "MyDS"
    access: direct
    url: "{{ ansible_role_grafana_url }}"
    grafana_user: "{{ ansible_role_grafana_security.admin_user }}"
    grafana_password: "{{ ansible_role_grafana_security.admin_password }}"
    use_proxy: false
    org_name: "{{ MyOrg }}"
    ds_type: loki
    ds_url: "{{ ansible_role_grafana_loki_url }}"
    tls_skip_verify: true
    tls_client_cert: "{{ grafana_cert.content | b64decode }}"
    tls_client_key: "{{ grafana_key.content | b64decode }}"
    # Missing option (suggested name)
    #tls_serverName: "{{ ansible_hostname }}"
    additional_json_data:
      httpHeaderName1: "X-Scope-OrgID"
    additional_secure_json_data:
      httpHeaderValue1: "{{ MyID }}"
    state: present
    is_default: false
```

##### EXPECTED RESULTS
![Capture d’écran 2024-08-01 151154](https://github.com/user-attachments/assets/bb7130ad-3c31-4de9-b9ed-b14eb9db31fd)

##### ACTUAL RESULTS
![Capture d’écran 2024-08-01 151021](https://github.com/user-attachments/assets/87d99aa0-ee01-406a-8b4b-a930e68440df)
