### ISSUE TITLE
Support creating dashboards in subfolders

### ISSUE THREAD

**Issue by BenjaminSchubert** [ansible-collections/community.grafana#410]
##### SUMMARY

New in Grafana 11, it is possible to nest folders for dashboards.

While this collection supports creating subfolders, it is not possible today to create a dashboard in a subfolder.

This is due to the grafana_dashboard plugin [searching for folder by name](https://github.com/ansible-collections/community.grafana/blob/main/plugins/modules/grafana_dashboard.py#L229) in a way that only returns available folders from the root.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
grafana_dashboard

##### ADDITIONAL INFORMATION

I can see multiple ways of implementing the feature:

1. By providing a new `folder_uid` explicitly, mutually exclusive with `folder`. The uid can be recovered with the `grafana_folder` plugin.
```yaml
- name: Import Grafana dashboard zabbix in a subfolder
  community.grafana.grafana_dashboard:
    grafana_url: http://grafana.company.com
    grafana_api_key: "{{ grafana_api_key }}"
    # Allow the user to force the exact folder UID in which to create the project
    folder_uid: <folder_uid>
    dashboard_url: https://grafana.com/api/dashboards/6098/revisions/1/download
```

2. By providing the parent_uid off the folder in which to search, retrievable with the `grafana_folder` again
```yaml
- name: Import Grafana dashboard zabbix in a subfolder
  community.grafana.grafana_dashboard:
    grafana_url: http://grafana.company.com
    grafana_api_key: "{{ grafana_api_key }}"
    # Allow the user to use a subfolder
    folder: public
    parent_uid: <public_folder_parent_uid>
    dashboard_url: https://grafana.com/api/dashboards/6098/revisions/1/download
```

3. By interpreting `/` in the folder names as a subfolder, and searching recursively
```yaml
- name: Import Grafana dashboard zabbix in a subfolder
  community.grafana.grafana_dashboard:
    grafana_url: http://grafana.company.com
    grafana_api_key: "{{ grafana_api_key }}"
    # Allow the user to use a subfolder
    folder: parent/public
    dashboard_url: https://grafana.com/api/dashboards/6098/revisions/1/download
```

Options 1 and 2 would be backward compatible
Options 3 would probably be the easiest to use
Options 2 doesn't seem to bring much compared to option 1

I'd be happy to implement, if we agree on what option would be preferable first.
