### ISSUE TITLE
contact poin creation failed just after organization is created

### ISSUE THREAD

**Issue by rosh0450** [ansible-collections/community.grafana#413]
##### SUMMARY
When you try create contact points just after creating organizations, it result in error with:

**statuscode**: 500
**message**: No alertmanager configuration present in this organization
**messageId**: alerting.notification.configMissing

Now the organization have been created and contact points created failed, when I rerrun my playbook, contact point creation is a success.

##### ISSUE TYPE
- Bug

##### COMPONENT NAME

Module name: `community.grafana.grafana_contact_point`

##### ANSIBLE VERSION

```paste below
2.16.11
```

##### COLLECTION VERSION

```paste below
# /home/rishavkumarj/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.grafana 2.1.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/rishavkumarj/repo/grafana/ansible.cfg
DEFAULT_LOG_PATH(/home/rishavkumarj/repo/grafana/ansible.cfg) = /home/rishavkumarj/repo/grafana/ansible.log
```

##### OS / ENVIRONMENT

NAME="AlmaLinux"
VERSION="9.4 (Seafoam Ocelot)"

##### STEPS TO REPRODUCE

variables:
```yaml
grafana_organizations:
  - name: org1
    state: present
    
grafana_contact_points:
  - name: mimir-alertmanager-tenant_okd
    type: alertmanager
    alertmanager_url: http://mimir-gateway.mimir.svc.cluster.local:80/alertmanager
    alertmanager_username: tenant_okd
    alertmanager_password: "{{ lookup('file', 'objects/secrets/tenant_okd') }}"
    org_name: org1
    uid: mimir-alertmanager-tenant_okd
    disable_resolve_message: false
    validate_certs: false
```

playbook:
```yaml
---
- name: Grafana
  roles:
    - role: community.grafana.grafana
```

##### EXPECTED RESULTS

Organizations and contact points should be created/configured.

##### ACTUAL RESULTS

Organization got created.
Contact points creation failed.

```paste below

```
