### ISSUE TITLE
grafana_dashboard: absent dont work because of a timeout

### ISSUE THREAD

**Issue by SaschaP95** [ansible-collections/community.grafana#414]
##### SUMMARY
Problem is that large grafana dashboards take longer to gets deleted and a internal timeout hits.
I have a large dashboard that takes some time to gets deleted via Grafana UI or a curl command. 
With the Ansible module I can not delete the dashboard at all because of an timeout.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.grafana.grafana_dashboard

##### ANSIBLE VERSION

```
Ansible EE 2.17
```

##### COLLECTION VERSION

```
2.1.0 or 2.0.0 not sure

```

##### CONFIGURATION

```
don't have it

```

##### STEPS TO REPRODUCE

```
- name: Delete dashboards not on source Grafana instance {{ grafana_instances }}
  community.grafana.grafana_dashboard:
    grafana_url: https://{{ hostvars[grafana_instances].ansible_host }}
    grafana_api_key: "{{ hostvars[grafana_instances].grafana_sa }}"
    uid: "{{ item }}"
    state: absent
    validate_certs: false
  loop: "{{ grafana_dest_search_result.json | selectattr('type', 'equalto', 'dash-db') | map(attribute='uid') | list }}"
  delegate_to: localhost
  when: grafana_dest_search_result.json | selectattr('type', 'equalto', 'dash-db') | map(attribute='uid') | list | length > 0
  loop_control:
    loop_var: item

```

##### EXPECTED RESULTS

To gets this one large dashboard also deleted like the other onces

##### ACTUAL RESULTS

It fails on the large dashboard, without this one it runs 
```
```

```
"msg": "error : Unable to update the dashboard XXXXX : {'url': 'https://XXXXX/api/dashboards/uid/XXXXXX', 'status': -1, 'msg': 'Connection failure: The read operation timed out'}",

```
