### ISSUE TITLE
Directly pass dashboard content

### ISSUE THREAD

**Issue by Hipska** [ansible-collections/community.grafana#417]
##### SUMMARY
Having the option to directly pass the dashboard content would eliminate the need to first create a file on the local filesystem.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.grafana.grafana_dashboard

##### ADDITIONAL INFORMATION
The dashboard definition could come from a ansible var (object or JSON string) or directly passed to the task.

```yaml
- name: Import Grafana dashboard foo from ansible var object
  community.grafana.grafana_dashboard:
    grafana_url: http://grafana.company.com
    grafana_api_key: "{{ grafana_api_key }}"
    state: present
    content: "{{ foo_dashboard }}"

- name: Import Grafana dashboard foo from json string
  community.grafana.grafana_dashboard:
    grafana_url: http://grafana.company.com
    grafana_api_key: "{{ grafana_api_key }}"
    state: present
    content: >
      {
        "title": "Foo",
        "style": "dark",
        ...
      }
```
