### ISSUE TITLE
Support for Loki Datasource

### ISSUE THREAD

**Issue by Robinhuett** [ansible-collections/community.grafana#92]
##### SUMMARY
Support for Loki Datasources in grafana_datasource module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
grafana_datasource

##### ADDITIONAL INFORMATION
Currently it's not possible to add a loki datasource with the grafana_datasource module in this collection.

It would be nice to add one with a task like this:
```yaml
- name: Ensure loki datasource exists.
  grafana_datasource:
    name: "datasource-loki"
    grafana_url: "https://grafana.company.com"
    grafana_user: "admin"
    grafana_password: "xxxxxx"
    org_id: "1"
    ds_type: "loki"
    ds_url: "https://loki.company.com:3100"
```

I took a brief look at the [grafana_datasource](https://github.com/ansible-collections/community.grafana/blob/master/plugins/modules/grafana_datasource.py) module and it seems at first glance that it just has to be added here: https://github.com/ansible-collections/community.grafana/blob/5ecea6c4ffd91dde5b7ce78478a646c3880817e8/plugins/modules/grafana_datasource.py#L556-L565
If so, I can open a PR for this.
